travis:
  secure:
    BINSTAR_TOKEN: irSEWU7/u7hltOZ+ycX1vxFX0QDwp0fF7BGOcs3gDRbt7NqwG35XtFd+IAxV1HzUfgwuOS+G8zRLgCfJtZ91kl9LTmeYkdClzpkw4Sxf77tY8qqv8XHWjMJrZeW+LdANMDIjJGPIxELKliXsbm9PrBCMGgx00kuQdGdAQ32dFDabd2iYrQ6sex4B4g0n82KZuULhdLEtz5ZZnhVi9QWJ5t5r49LJxY3m1zK95XSgyoYCuLSzGi262ugY2gCs0gisTNifV00tbom7ZAikRzYpKHaVz0BldTMCxkjz7MX6UVjLw2tsOiog1aOYqreGScFspW0T4ZDLP8nxKjledmPwWrEDFI4UK6Ic1MY5zgYCNJBjBXFwwDczTDapTVeUKYouaYquplyFoHkvst9xIWuWwU8zldfA7EXW3c9+B+r5LaIjE+vH8iaBtdMyenVlinEyAisZ1ViA1+SBFo6AneGfOTIvRejIcAKEm1XnZNtojcvkoL8fdECYW3/0BB2QmA+nAokSgUz/AXCcN7TzwB+6r31fKuhtiAwLJc+DxefOuzVFWM1frlsV8T+FmQDph6x96IKXa9txsvTPSq5bqdZmAaUen3wzYHAC5Hi7K9Ehl1tGBQS11rkBUNLlsli7VrcoUujnpp5Ym8U9i7GiqQwVbnLYWUivbDtdfeiqtr2xzZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
